# Generated by Django 5.2.4 on 2025-09-10 02:06

import accounts.managers
import accounts.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=100, verbose_name='Governorate')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('building_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Building Number')),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apartment Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PHONE_VERIFICATION', 'Phone Verification'), ('EMAIL_VERIFICATION', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset')], max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=accounts.models.otp_expiry_default)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_country', models.CharField(default='20', max_length=5, verbose_name='Country Code')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone (E.164)')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('address', models.TextField(blank=True, default='', verbose_name='Address')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Phone Verified')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='الحساب موقوف')),
                ('suspension_reason', models.TextField(blank=True, null=True, verbose_name='سبب الإيقاف')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إدارية')),
                ('custom_notification', models.CharField(blank=True, max_length=255, null=True, verbose_name='إشعار مخصص للعميل')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]

