# Generated by Django 5.2.4 on 2025-10-31 15:48

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]

