# Generated by Django 5.2.4 on 2025-12-11 08:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount_applies_to_services',
            field=models.BooleanField(default=False, help_text='إذا تم تفعيله، سيتم تطبيق الخصم على الذبح والتوصيل أيضاً. إذا لا، سيطبق على سعر الماشية فقط.', verbose_name='الخصم يشمل الخدمات'),
        ),
        migrations.AddField(
            model_name='user',
            name='special_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='نسبة خصم تطبق تلقائياً على طلبات هذا العميل', max_digits=5, verbose_name='نسبة خصم خاص (%)'),
        ),
    ]

