# Generated by Django 5.2.4 on 2025-12-11 09:46

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_discount_applies_to_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الخصم'),
        ),
        migrations.AddField(
            model_name='user',
            name='discount_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء الخصم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='discount_applies_to_services',
            field=models.BooleanField(default=False, verbose_name='الخصم يشمل الخدمات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='special_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة خصم خاص (%)'),
        ),
    ]

