# Generated by Django 5.2.4 on 2025-12-11 11:16

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_discount_end_date_user_discount_start_date_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount_custom_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رسالة الشريط المخصصة'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_discount_active',
            field=models.BooleanField(default=True, verbose_name='تفعيل الخصم الخاص'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customer_user_groups', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]

