# Generated by Django 5.2.4 on 2025-12-11 12:38

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_discount_custom_message_user_is_discount_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_global_discount',
            field=models.BooleanField(default=True, verbose_name='سماح بالخصم العام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_discount_active',
            field=models.BooleanField(default=False, verbose_name='تفعيل الخصم الخاص (يلغي العام)'),
        ),
    ]

