# Generated by Django 5.2.4 on 2025-12-30 01:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_allow_global_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم النشاط التجاري'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_corporate',
            field=models.BooleanField(default=False, help_text='تفعيل هذا الخيار يعني أن العميل فندق، مطعم، أو جزارة', verbose_name='حساب شركة/أعمال'),
        ),
    ]

