# Generated by Django 5.2.4 on 2026-03-09 23:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_business_name_user_is_corporate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount_max_animals',
            field=models.PositiveIntegerField(default=0, verbose_name='أقصى عدد مواشي للخصم الخاص (0=مفتوح)'),
        ),
        migrations.AddField(
            model_name='user',
            name='discount_used_animals',
            field=models.PositiveIntegerField(default=0, verbose_name='المواشي المستخدمة (خصم خاص)'),
        ),
        migrations.AddField(
            model_name='user',
            name='global_discount_used_animals',
            field=models.PositiveIntegerField(default=0, verbose_name='المواشي المستخدمة (خصم عام)'),
        ),
    ]

