# Generated by Django 5.2.4 on 2025-09-10 02:06

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='إشعار', max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('order', 'Order'), ('payment', 'Payment'), ('cart', 'Cart'), ('livestock', 'Livestock'), ('reservation', 'Reservation'), ('general', 'General')], default='general', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.user')),
            ],
        ),
    ]

