# Generated by Django 5.2.4 on 2025-09-10 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('preparing', 'قيد التحضير'), ('shipped', 'تم الشحن'), ('delivered', 'تم التوصيل'), ('completed', 'مكتمل'), ('canceled', 'ملغي')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي تكلفة الخدمات')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المتبقي')),
                ('delivery_type', models.CharField(blank=True, choices=[('delivery', 'توصيل للمنزل'), ('pickup', 'استلام من المزرعة')], max_length=20, null=True, verbose_name='طريقة الاستلام')),
                ('source', models.CharField(choices=[('online_store', 'المتجر الإلكتروني'), ('on_farm', 'بيع مباشر من المزرعة')], default='online_store', max_length=20, verbose_name='مصدر الطلب')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم/الاستلام')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='عنوان التوصيل (بيع مباشر)')),
                ('payment_method', models.CharField(choices=[('cash', 'كاش'), ('card', 'بطاقة ائتمان/فيزا')], default='cash', max_length=20, verbose_name='طريقة الدفع المسجلة')),
                ('has_slaughter_service', models.BooleanField(default=False, editable=False)),
                ('created_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة (موظف)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost of services for this specific animal.', max_digits=10)),
                ('selected_services', models.JSONField(blank=True, default=dict, help_text="Services chosen for this specific animal, e.g., {'slaughter': true}")),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.animal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]

