# Generated by Django 5.2.4 on 2025-10-31 15:47

from django.db import migrations, models
import django.db.models.deletion

#      NULL
def convert_empty_string_to_null(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    #            NULL
    Order.objects.filter(delivery_address="").update(delivery_address=None)

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [

        migrations.RunPython(convert_empty_string_to_null, migrations.RunPython.noop),

        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address', verbose_name='عنوان التوصيل'),
        ),
    ]
