# Generated by Django 5.2.4 on 2025-11-06 23:19

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_address'),
        ('livestock', '0002_animal_internal_notes_animal_source_farm_and_more'),
        ('orders', '0002_auto_20251031_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات على الطلب'),
        ),
        migrations.CreateModel(
            name='SpecialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_specs', models.JSONField(default=dict, verbose_name='المواصفات المطلوبة')),
                ('status', models.CharField(choices=[('pending', 'قيد البحث'), ('sourced', 'تم توفيرها'), ('confirmed', 'مؤكدة من العميل'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_special_request', to='orders.order')),
                ('sourced_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='livestock.animal', verbose_name='الحيوان الذي تم توفيره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_requests', to='accounts.user', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب خاص',
                'verbose_name_plural': 'الطلبات الخاصة (الماشية المطلوبة)',
                'ordering': ['-created_at'],
            },
        ),
    ]

