# Generated by Django 5.2.4 on 2025-12-11 08:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_share_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الخصم المطبق'),
        ),
    ]

