# Generated by Django 5.2.4 on 2025-12-12 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_applied_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100, verbose_name='اسم السائق')),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف السائق')),
                ('car_plate', models.CharField(max_length=20, verbose_name='رقم السيارة')),
                ('butcher_names', models.TextField(blank=True, help_text='يمكنك كتابة أكثر من اسم', null=True, verbose_name='أسماء الجزارين')),
                ('status', models.CharField(choices=[('pending', 'قيد التجهيز'), ('out_for_delivery', 'خرجت للتوصيل'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الرحلة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_shipments', to=settings.AUTH_USER_MODEL, verbose_name='المشرف المسؤول')),
            ],
            options={
                'verbose_name': 'رحلة / طلعة',
                'verbose_name_plural': 'الرحلات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shipment', verbose_name='الرحلة'),
        ),
    ]

