# Generated by Django 5.2.4 on 2025-12-15 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_allow_global_discount_and_more'),
        ('livestock', '0005_animal_location'),
        ('orders', '0006_shipment_order_shipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelOptions(
            name='specialrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Special Request', 'verbose_name_plural': 'Special Requests'},
        ),
        migrations.AlterField(
            model_name='order',
            name='applied_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By (Employee)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address', verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('delivery', 'Home Delivery'), ('pickup', 'Farm Pickup')], max_length=20, null=True, verbose_name='Delivery Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deposit Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit Card')], default='cash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remaining Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Service Cost'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shipment', verbose_name='Shipment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('online_store', 'Online Store'), ('on_farm', 'On Farm POS')], default='online_store', max_length=20, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.user', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='deposit_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deposit per Item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='share_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Share Quantity'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='butcher_names',
            field=models.TextField(blank=True, help_text='You can write multiple names', null=True, verbose_name='Butchers Names'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='car_plate',
            field=models.CharField(max_length=20, verbose_name='Car Plate'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Shipment Date'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='driver_name',
            field=models.CharField(max_length=100, verbose_name='Driver Name'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Driver Phone'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('out_for_delivery', 'Out for Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='requested_specs',
            field=models.JSONField(default=dict, verbose_name='Requested Specs'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='sourced_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='livestock.animal', verbose_name='Sourced Animal'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Search'), ('sourced', 'Sourced'), ('confirmed', 'Confirmed by Customer'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_requests', to='accounts.user', verbose_name='Customer'),
        ),
    ]

