# Generated by Django 5.2.4 on 2025-12-16 18:40

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_options_alter_shipment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: شيفروليه جامبو أبيض', max_length=100, verbose_name='اسم/وصف السيارة')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('vehicle_type', models.CharField(choices=[('livestock', 'نقل مواشي (حي)'), ('refrigerated', 'مبرد (لحوم)'), ('general', 'نقل عام/إداري')], default='livestock', max_length=20, verbose_name='نوع السيارة')),
                ('ownership', models.CharField(choices=[('owned', 'مملوكة للمزرعة'), ('rented', 'إيجار')], default='owned', max_length=20, verbose_name='الملكية')),
                ('capacity_description', models.CharField(blank=True, help_text='مثال: 5 عجول أو 20 خروف', max_length=255, verbose_name='وصف الحمولة')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='السائق الافتراضي')),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم السائق')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاحة للعمل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مركبة/سيارة',
                'verbose_name_plural': 'أسطول السيارات',
            },
        ),
    ]

