# Generated by Django 5.2.4 on 2025-12-16 18:48

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='orders.vehicle', verbose_name='السيارة المستخدمة'),
        ),
    ]

