# Generated by Django 5.2.4 on 2025-12-16 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_allow_global_discount_and_more'),
        ('livestock', '0005_animal_location'),
        ('orders', '0009_shipment_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'عنصر الطلب', 'verbose_name_plural': 'عناصر الطلب'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'الرحلة', 'verbose_name_plural': 'الرحلات'},
        ),
        migrations.AlterModelOptions(
            name='specialrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب خاص', 'verbose_name_plural': 'الطلبات الخاصة'},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='car_plate',
        ),
        migrations.AlterField(
            model_name='order',
            name='applied_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة الخصم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة (موظف)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address', verbose_name='عنوان التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('delivery', 'توصيل للمنزل'), ('pickup', 'استلام من المزرعة')], max_length=20, null=True, verbose_name='نوع التوصيل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deposit_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'كاش'), ('card', 'بطاقة ائتمان/فيزا'), ('paymob', 'أونلاين')], default='cash', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المتبقي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الخدمات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.shipment', verbose_name='الرحلة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('online_store', 'المتجر الإلكتروني'), ('on_farm', 'نقطة بيع مباشرة')], default='online_store', max_length=20, verbose_name='مصدر الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق (بانتظار الدفع)'), ('confirmed', 'مؤكد (جاهز للتجهيز)'), ('processing', 'قيد التجهيز'), ('ready_for_shipment', 'جاهز للشحن'), ('out_for_delivery', 'في الطريق للتوصيل'), ('delivered', 'تم التوصيل'), ('completed', 'مكتمل'), ('canceled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='السعر الإجمالي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.user', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.animal', verbose_name='الحيوان'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='deposit_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='عربون للقطعة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر للقطعة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_services',
            field=models.JSONField(blank=True, default=dict, help_text="الخدمات المختارة لهذا الحيوان المحدد، مثال: {'slaughter': true}"),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='service_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='التكلفة الإجمالية للخدمات لهذا الحيوان المحدد.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='share_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='كمية المشاركة'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='butcher_names',
            field=models.TextField(blank=True, help_text='يمكنك كتابة أكثر من اسم', null=True, verbose_name='أسماء الجزارين'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الرحلة'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='driver_name',
            field=models.CharField(max_length=100, verbose_name='اسم السائق'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف السائق'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الرحلة'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد التجهيز'), ('out_for_delivery', 'خرجت للتوصيل'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_shipments', to=settings.AUTH_USER_MODEL, verbose_name='المشرف المسؤول'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='requested_specs',
            field=models.JSONField(default=dict, verbose_name='المواصفات المطلوبة'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='sourced_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='livestock.animal', verbose_name='الحيوان الذي تم العثور عليه'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد البحث'), ('sourced', 'تم العثور عليها'), ('confirmed', 'مؤكد من العميل'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_requests', to='accounts.user', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف السائق'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('livestock', 'نقل مواشي (حية)'), ('refrigerated', 'مبردة (لحوم)'), ('general', 'نقل عام/إداري')], default='livestock', max_length=20, verbose_name='نوع السيارة'),
        ),
    ]

