# Generated by Django 5.2.4 on 2026-01-01 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_business_name_user_is_corporate'),
        ('orders', '0010_alter_orderitem_options_alter_shipment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_details', models.JSONField(help_text='قائمة تحتوي على العناصر المطلوبة مع الوزن والكمية والخدمات', verbose_name='تفاصيل الطلبية')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('quoted_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر المقترح')),
                ('quoted_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='العربون المطلوب')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوصيل المتوقع')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('quoted', 'تم التسعير (بانتظار الدفع)'), ('paid', 'تم الدفع (بانتظار التخصيص)'), ('fulfilled', 'تم التنفيذ (تحول لطلب)'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_source', to='orders.order', verbose_name='الطلب المحول')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_requests', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_requests', to='accounts.user', verbose_name='العميل')),
            ],
        ),
    ]

