# Generated by Django 5.2.4 on 2026-01-06 20:29

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_businessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extra_parts_preference',
            field=models.CharField(choices=[('receive', 'استلام (مع اللحم)'), ('donate', 'تبرع (للمحتاجين)'), ('sell', 'بيع (خصم من الثمن) - غير متاح للأضحية')], default='receive', help_text='لأضاحي التشارك: استلام أو تبرع فقط (توزيع بالقرعة). للتشارك العادي: متاح البيع.', max_length=20, verbose_name='مصير الأجزاء الإضافية (الرأس/السقط)'),
        ),
        migrations.AlterField(
            model_name='businessrequest',
            name='request_details',
            field=models.JSONField(help_text='قائمة تحتوي على العناصر المطلوبة', verbose_name='تفاصيل الطلبية'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_services',
            field=models.JSONField(blank=True, default=dict, help_text='الخدمات المختارة'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='service_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='التكلفة الإجمالية للخدمات', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='وصف الحمولة'),
        ),
    ]

