# Generated by Django 5.2.4 on 2026-02-03 01:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_extra_parts_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pipeline',
            field=models.CharField(choices=[('M', 'M'), ('S', 'S'), ('G', 'G')], default='M', max_length=1, verbose_name='كود الماسورة'),
        ),
    ]

