# Generated by Django 5.2.4 on 2026-02-04 23:48

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='listing_section',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='قسم الإدراج'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pipeline',
            field=models.CharField(choices=[('M', 'M - سوق المواشي'), ('S', 'S - الأضاحي'), ('G', 'G - تشارك عام')], default='M', max_length=1, verbose_name='الماسورة'),
        ),
    ]

