# Generated by Django 5.2.4 on 2026-02-05 00:26

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_listing_section_alter_orderitem_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='listing_section',
            field=models.CharField(blank=True, help_text='مثال: full_sale, adahi_pool, adahi_full, adahi_group, shares', max_length=20, null=True, verbose_name='قسم الإدراج داخل الماسورة'),
        ),
    ]

