# Generated by Django 5.2.4 on 2026-03-09 23:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_orderitem_listing_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_counted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]

