# Generated by Django 5.2.4 on 2026-03-11 21:12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_discount_counted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_photos/', verbose_name='صورة التسليم (اختياري)'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paperwork_received',
            field=models.BooleanField(default=False, verbose_name='تم استلام الورق الأصلي من السائق'),
        ),
        migrations.AddField(
            model_name='order',
            name='signed_receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_receipts/', verbose_name='صورة الإيصال الممضي'),
        ),
    ]

