# Generated by Django 5.2.4 on 2026-03-14 21:59

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_delivery_photo_order_is_paperwork_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق (بانتظار الدفع)'), ('confirmed', 'مؤكد (جاهز للتجهيز)'), ('processing', 'قيد التجهيز'), ('packaging', 'في الثلاجة/التغليف'), ('ready_for_shipment', 'جاهز للشحن'), ('out_for_delivery', 'في الطريق للتوصيل'), ('delivered', 'تم التوصيل'), ('completed', 'مكتمل'), ('canceled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]

