# Generated by Django 5.2.4 on 2026-03-15 02:47

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('pickup', 'جلب من مورد'), ('slaughter', 'نقل للمجزر'), ('delivery', 'توصيل للعميل')], default='delivery', max_length=20, verbose_name='نوع الرحلة'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد التجهيز'), ('out_for_delivery', 'في الطريق'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]

