# Generated by Django 5.2.4 on 2026-03-15 05:11

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_shipment_shipment_type_alter_shipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='كود التسليم (OTP)'),
        ),
    ]

