# Generated by Django 5.2.4 on 2026-03-15 20:41

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_delivery_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='butcher_names',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_type',
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_step_index',
            field=models.IntegerField(default=0, verbose_name='المحطة الحالية للسائق'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_lat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط العرض (GPS)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_lng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خط الطول (GPS)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث للموقع'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='route_plan',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='مسار الرحلة المرتب'),
        ),
    ]

