# Generated by Django 5.2.4 on 2026-03-15 20:53

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_shipment_butcher_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='butcher_names',
            field=models.TextField(blank=True, null=True, verbose_name='أسماء الجزارين'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(default='delivery', max_length=20, verbose_name='نوع الرحلة'),
        ),
    ]

