# Generated by Django 5.2.4 on 2026-03-21 04:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_shipment_butcher_names_shipment_shipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrival_sms_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال رسالة السائق'),
        ),
        migrations.AddField(
            model_name='order',
            name='otp_sent_count',
            field=models.IntegerField(default=0, verbose_name='عدد مرات إرسال الـ OTP'),
        ),
    ]

