# Generated by Django 5.2.4 on 2026-03-21 05:48

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_arrival_sms_sent_at_order_otp_sent_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='history_log',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='سجل تحركات السائق'),
        ),
    ]

