# Generated by Django 5.2.4 on 2026-03-25 02:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_shipment_history_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='request_slaughter_video',
            field=models.BooleanField(default=False, verbose_name='طلب تصوير الذبح'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='slaughter_video',
            field=models.FileField(blank=True, null=True, upload_to='slaughter_videos/', verbose_name='فيديو الذبح للعميل'),
        ),
    ]

