# Generated by Django 5.2.4 on 2026-03-26 09:04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_orderitem_request_slaughter_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='customer_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات العميل'),
        ),
    ]

