# Generated by Django 5.2.4 on 2026-03-31 16:17

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_businessrequest_customer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pricing_model',
            field=models.CharField(default='care_fee', max_length=20, verbose_name='نظام التسعير المتبع'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='actual_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الوزن الفعلي وقت التسليم'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر المبدئي وقت الحجز'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق (بانتظار الدفع)'), ('confirmed', 'مؤكد (جاهز للتجهيز)'), ('requires_action', 'يتطلب تدخل (نواقص) ⚠️'), ('processing', 'قيد التجهيز'), ('packaging', 'في الثلاجة/التغليف'), ('ready_for_shipment', 'جاهز للشحن'), ('out_for_delivery', 'في الطريق للتوصيل'), ('delivered', 'تم التوصيل'), ('completed', 'مكتمل'), ('canceled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]

