# Generated by Django 5.2.4 on 2026-04-01 14:26

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_pricing_model_orderitem_actual_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الوزن التقديري وقت الحجز'),
        ),
    ]

