# Generated by Django 5.2.4 on 2026-04-21 01:17

import django.core.validators
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_orderitem_original_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='slaughter_video',
            field=models.FileField(blank=True, null=True, upload_to='slaughter_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])], verbose_name='فيديو الذبح للعميل'),
        ),
    ]

