# Generated by Django 5.2.4 on 2026-01-25 02:39

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_services',
            field=models.JSONField(blank=True, default=dict, help_text='خيارات الخدمات التي اختارها المستخدم لهذا العنصر', null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='share_quantity',
            field=models.PositiveIntegerField(default=1, help_text='عدد الأسهم المطلوبة إذا كان الحيوان قابلاً للمشاركة'),
        ),
    ]

