# Generated by Django 5.2.4 on 2026-02-03 01:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_selected_services_cartitem_share_quantity'),
        ('livestock', '0021_alter_animallisting_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pipeline',
            field=models.CharField(choices=[('M', 'M'), ('S', 'S'), ('G', 'G')], default='M', help_text='الماسورة التي تم الشراء منها', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'animal', 'pipeline')},
        ),
    ]

