# Generated by Django 5.2.4 on 2025-09-10 02:06

import django.db.models.deletion
import livestock.models
import uuid
from decimal import Decimal
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, unique=True, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=50, unique=True, verbose_name='الاسم (إنجليزي / منسوب للرابط)')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='الرابط (Slug)')),
                ('standard_birth_cost', models.DecimalField(decimal_places=2, default=0, help_text='التكلفة الدفترية التقديرية للمولود الجديد من هذه الفئة.', max_digits=10, verbose_name='تكلفة الولادة القياسية')),
                ('daily_care_fee', models.DecimalField(decimal_places=2, default=50.0, help_text='التكلفة اليومية لرعاية حيوان من هذه الفئة بعد انتهاء الفترة المجانية.', max_digits=10, verbose_name='تكلفة الرعاية اليومية')),
            ],
        ),
        migrations.CreateModel(
            name='ClientServiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('show_to_client', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_days', models.JSONField(default=list)),
                ('pickup_days', models.JSONField(default=list)),
                ('delivery_days_ahead', models.PositiveIntegerField(default=7)),
                ('pickup_days_ahead', models.PositiveIntegerField(default=7)),
                ('preparation_days', models.PositiveIntegerField(default=3, help_text='عدد أيام التحضير قبل التوصيل/الاستلام')),
                ('free_care_days', models.PositiveIntegerField(default=4, help_text='عدد أيام الرعاية المجانية المضمنة في السعر بعد الحجز.')),
                ('min_deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='الحد الأدنى لنسبة العربون المطلوب (مثال: 0.20 لـ 20%)', max_digits=5)),
                ('service_deposit_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='نسبة العربون المطلوبة إذا كان الطلب يتضمن خدمات ذبح (مثال: 0.50 لـ 50%)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='اسم الحيوان')),
                ('sex', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10)),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('entry_type', models.CharField(choices=[('purchased', 'تم شراؤه'), ('born_on_farm', 'مولود بالمزرعة')], default='purchased', max_length=20, verbose_name='مصدر الحيوان')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, help_text='للمشتريات: أدخل سعر الشراء. للمواليد: سيتم ملؤه تلقائياً من تكلفة الفئة القياسية.', max_digits=10, verbose_name='التكلفة الدفترية (سعر الشراء أو تكلفة الولادة)')),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('price_egp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_egp', models.DecimalField(decimal_places=2, default=0, help_text='مبلغ العربون الافتراضي للحيوان (إذا لم يُحدد نسبة)', max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='نسبة الخصم (%)', max_digits=5)),
                ('is_offer', models.BooleanField(default=False, help_text='هل الحيوان عليه عرض؟')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('reserved', 'محجوز'), ('sold', 'مباع'), ('lost', 'مفقود/نافد')], db_index=True, default='available', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=livestock.models.animal_main_upload)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to=livestock.models.animal_qr_code_upload, verbose_name='صورة QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'sex': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_father', to='livestock.animal', verbose_name='الأب')),
                ('mother', models.ForeignKey(blank=True, limit_choices_to={'sex': 'female'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_mother', to='livestock.animal', verbose_name='الأم')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='livestock.category')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=livestock.models.animal_image_upload)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='livestock.animal')),
            ],
        ),
        migrations.CreateModel(
            name='ClientServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='livestock.clientservicequestion')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر التوصيل (جنيه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ظاهر للعميل؟')),
                ('governorate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.governorate', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'منطقة توصيل',
                'verbose_name_plural': 'مناطق التوصيل',
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['status', 'price_egp'], name='livestock_a_status_a1538b_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['status'], name='livestock_a_status_ea60fe_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['status', 'birth_date'], name='livestock_a_status_f1d9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['status', 'category'], name='livestock_a_status_c1d1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['is_offer'], name='livestock_a_is_offe_68bef9_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['-created_at'], name='livestock_a_created_9b05d2_idx'),
        ),
    ]

