# Generated by Django 5.2.4 on 2025-10-23 20:55

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
        ('management', '0004_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إدارية (لا تظهر للعميل)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='source_farm',
            field=models.ForeignKey(blank=True, help_text='إذا كان الحيوان من مزرعة خارجية، اختر المورد من هنا. اتركه فارغاً إذا كان من مزارعنا.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.supplier', verbose_name='المزرعة الموردة (إن وجد)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الحيوان عند المورد'),
        ),
    ]

