# Generated by Django 5.2.4 on 2025-12-10 18:03

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_animal_internal_notes_animal_source_farm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_shareable',
            field=models.BooleanField(default=False, help_text='هل يمكن بيع هذا الحيوان كأسهم؟', verbose_name='قابل للمشاركة'),
        ),
        migrations.AddField(
            model_name='animal',
            name='max_shares',
            field=models.PositiveIntegerField(default=1, help_text='العدد الأقصى للمشاركين (افتراضي 1 يعني غير قابل للمشاركة)', verbose_name='عدد الأسهم الكلي'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_max_shares',
            field=models.PositiveIntegerField(default=1, help_text='العدد الافتراضي للأفراد في حالة المشاركة (مثلاً 7 للعجول، 1 للخراف).', verbose_name='عدد الأسهم الافتراضي'),
        ),
    ]

