# Generated by Django 5.2.4 on 2025-12-11 14:12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_animal_is_shareable_animal_max_shares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='weight_variance_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='الرقم الذي سيظهر للعميل (قد يزيد أو يقل الوزن بمقدار ...)', max_digits=5, verbose_name='مقدار تفاوت الوزن المسموح (كجم)'),
        ),
    ]

