# Generated by Django 5.2.4 on 2025-12-12 07:11

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_category_weight_variance_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='location',
            field=models.CharField(blank=True, help_text='مثال: عنبر 1، حظيرة 3', max_length=100, null=True, verbose_name='المكان في المزرعة'),
        ),
    ]

