# Generated by Django 5.2.4 on 2025-12-19 20:12

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_animal_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='has_defect',
            field=models.BooleanField(default=False, help_text='عيوب تمنع الأضحية (عوراء، عرجاء، مريضة، هزيلة..)', verbose_name='به عيب شرعي'),
        ),
        migrations.AddField(
            model_name='animal',
            name='is_hidden_from_store',
            field=models.BooleanField(default=False, help_text='يظهر فقط في الداشبورد', verbose_name='إخفاء من المتجر'),
        ),
        migrations.AddField(
            model_name='category',
            name='logic_type',
            field=models.CharField(choices=[('sheep', 'ضأن (خروف)'), ('goat', 'ماعز'), ('cow', 'بقر/جاموس'), ('camel', 'إبل (جمال)'), ('other', 'غير محدد / أخرى')], default='other', help_text='يحدد قواعد السن الشرعي للأضحية', max_length=10, verbose_name='نوع المنطق الشرعي'),
        ),
        migrations.CreateModel(
            name='CategoryGrowthRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='من وزن (كجم)')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='إلى وزن (كجم)')),
                ('daily_increase', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='معدل الزيادة اليومي (كجم)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_rates', to='livestock.category')),
            ],
            options={
                'verbose_name': 'معدل نمو',
                'verbose_name_plural': 'معدلات النمو',
                'ordering': ['min_weight'],
            },
        ),
    ]

