# Generated by Django 5.2.4 on 2025-12-21 17:27

import livestock.models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_animal_has_defect_animal_is_hidden_from_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=livestock.models.category_image_upload, verbose_name='صورة الفئة'),
        ),
    ]

