# Generated by Django 5.2.4 on 2026-01-04 19:57

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0008_adahi_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='adahigroup',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت انتهاء المجموعة'),
        ),
    ]

