# Generated by Django 5.2.4 on 2026-01-05 00:23

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0009_adahigroup_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_adahi',
            field=models.BooleanField(default=False, help_text='يظهر في صفحة الأضاحي (سواء مسبح عام أو مجموعة خاصة)', verbose_name='مخصص للأضاحي'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_adahi_pool',
            field=models.BooleanField(default=False, help_text='إذا كان ضمن مسبح الأضاحي العام', verbose_name='مسبح أضاحي عام'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_shareable',
            field=models.BooleanField(default=False, help_text='يظهر في صفحة التشارك العادية', verbose_name='تشارك عام (عقيقة/صدقة)'),
        ),
    ]

