# Generated by Django 5.2.4 on 2026-01-15 12:43

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0010_animal_is_adahi_alter_animal_is_adahi_pool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='shares_section_max_shares',
            field=models.PositiveIntegerField(default=0, help_text='هذا الرقم يستخدم فقط عند العرض في صفحة Shared Purchases. عند البيع الفعلي، سينتقل هذا الرقم إلى max_shares.', verbose_name='عدد أسهم التشارك (المخصص)'),
        ),
    ]

