# Generated by Django 5.2.4 on 2026-01-15 20:02

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0011_animal_shares_section_max_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='first_sale_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ أول بيع'),
        ),
        migrations.AddField(
            model_name='animal',
            name='lock_type',
            field=models.CharField(choices=[('none', 'غير مقفل'), ('full_sale', 'بيع كامل'), ('shares', 'تشارك عادي'), ('adahi_pool', 'مسبح أضاحي'), ('private_group', 'مجموعة خاصة')], default='none', help_text='يحدد أين يظهر الحيوان بعد أول بيع', max_length=20, verbose_name='نوع القفل الحالي'),
        ),
    ]

