# Generated by Django 5.2.4 on 2026-01-21 20:29

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0012_animal_first_sale_at_animal_lock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='is_adahi_pool',
            field=models.BooleanField(default=False, help_text='إذا تم تفعيله، سيظهر هذا الحيوان في القسم الثاني (مشاركة عامة) في صفحة الأضاحي.', verbose_name='مسبح أضاحي عام'),
        ),
    ]

