# Generated by Django 5.2.4 on 2026-01-25 21:39

import livestock.models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0013_alter_animal_is_adahi_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='image',
            field=models.FileField(upload_to=livestock.models.animal_image_upload, validators=[livestock.models.validate_file_extension], verbose_name='ملف (صورة/فيديو)'),
        ),
    ]

