# Generated by Django 5.2.4 on 2026-01-26 00:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0014_alter_animalimage_image'),
        ('management', '0021_jobopening_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='has_defect',
            field=models.BooleanField(default=False, verbose_name='به عيب شرعي'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_adahi',
            field=models.BooleanField(default=False, verbose_name='مخصص للأضاحي'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_adahi_pool',
            field=models.BooleanField(default=False, verbose_name='مسبح أضاحي عام'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_hidden_from_store',
            field=models.BooleanField(default=False, verbose_name='إخفاء من المتجر'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_shareable',
            field=models.BooleanField(default=False, verbose_name='تشارك عام (عقيقة/صدقة)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المكان في المزرعة'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='lock_type',
            field=models.CharField(choices=[('none', 'غير مقفل'), ('full_sale', 'بيع كامل'), ('shares', 'تشارك عادي'), ('adahi_pool', 'مسبح أضاحي'), ('private_group', 'مجموعة خاصة')], default='none', max_length=20, verbose_name='نوع القفل الحالي'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='max_shares',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الأسهم الكلي'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التكلفة الدفترية (سعر الشراء أو تكلفة الولادة)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='shares_section_max_shares',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد أسهم التشارك (المخصص)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='source_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.supplier', verbose_name='المزرعة الموردة (إن وجد)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='daily_care_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='تكلفة الرعاية اليومية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='default_max_shares',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الأسهم الافتراضي'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logic_type',
            field=models.CharField(choices=[('sheep', 'ضأن (خروف)'), ('goat', 'ماعز'), ('cow', 'بقر/جاموس'), ('camel', 'إبل (جمال)'), ('other', 'غير محدد / أخرى')], default='other', max_length=10, verbose_name='نوع المنطق الشرعي'),
        ),
        migrations.AlterField(
            model_name='category',
            name='standard_birth_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الولادة القياسية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight_variance_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='مقدار تفاوت الوزن المسموح (كجم)'),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='free_care_days',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='min_deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='preparation_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='service_deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5),
        ),
    ]

