# Generated by Django 5.2.4 on 2026-01-26 04:39

import livestock.models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0015_alter_animal_has_defect_alter_animal_is_adahi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=livestock.models.animal_video_upload, verbose_name='فيديو الحيوان'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=livestock.models.animal_main_upload, verbose_name='الصورة الرئيسية / الكافر'),
        ),
    ]

