# Generated by Django 5.2.4 on 2026-01-27 23:27

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0016_animal_video_alter_animal_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='animalimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
    ]

