# Generated by Django 5.2.4 on 2026-01-31 07:37

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0017_alter_animalimage_options_animalimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='deposit_egp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
    ]

