# Generated by Django 5.2.4 on 2026-01-31 07:52

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0018_alter_animal_deposit_egp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='deposit_egp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مبلغ العربون الافتراضي للحيوان (إذا لم يُحدد نسبة)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='نسبة الخصم (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_offer',
            field=models.BooleanField(default=False, help_text='هل الحيوان عليه عرض؟'),
        ),
    ]

