# Generated by Django 5.2.4 on 2026-02-01 05:11

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0019_alter_animal_deposit_egp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('livestock', 'سوق المواشي (كامل)'), ('adahi_pool', 'مسبح أضاحي (7 أسهم)'), ('general_shares', 'تشارك عام (عدد مرن)'), ('private_group', 'مجموعة خاصة')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي في هذا القسم')),
                ('total_shares', models.PositiveIntegerField(default=1, verbose_name='عدد الأسهم الكلي')),
                ('available_shares', models.PositiveIntegerField(default=1, verbose_name='الأسهم المتاحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='livestock.animal')),
            ],
            options={
                'verbose_name': 'عرض بيع',
                'verbose_name_plural': 'عروض البيع',
                'unique_together': {('animal', 'section')},
            },
        ),
    ]

