# Generated by Django 5.2.4 on 2026-02-03 01:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0020_animallisting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animallisting',
            options={'verbose_name': 'عرض بيع (ماسورة)', 'verbose_name_plural': 'عروض البيع (المواسير)'},
        ),
        migrations.AlterUniqueTogether(
            name='animallisting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='pipeline',
            field=models.CharField(choices=[('M', 'سوق المواشي (Market)'), ('S', 'الأضاحي (Sacrifices)'), ('G', 'تشارك عام (General Shares)')], default='M', max_length=5, verbose_name='كود الماسورة (G)'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر في هذه الماسورة'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='section',
            field=models.CharField(choices=[('livestock', 'بيع كامل'), ('adahi_pool', 'مسبح أضاحي'), ('private_group', 'مجموعة خاصة'), ('general_shares', 'تشارك عام')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='total_shares',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الأسهم الكلي (H)'),
        ),
        migrations.AlterUniqueTogether(
            name='animallisting',
            unique_together={('animal', 'pipeline', 'section')},
        ),
    ]

