# Generated by Django 5.2.4 on 2026-02-04 23:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_business_name_user_is_corporate'),
        ('livestock', '0021_alter_animallisting_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adahigroup',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='is_adahi',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='is_adahi_pool',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='lock_type',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='max_shares',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='shares_section_max_shares',
        ),
        migrations.AddField(
            model_name='adahigroup',
            name='listing',
            field=models.OneToOneField(default=1, limit_choices_to={'section': 'adahi_group'}, on_delete=django.db.models.deletion.CASCADE, related_name='adahi_group', to='livestock.animallisting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animallisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animallisting',
            name='group_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='كود المجموعة'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='group_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user', verbose_name='منشئ المجموعة'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='group_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء المجموعة'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_shareable',
            field=models.BooleanField(default=False, verbose_name='قابل للتشارك (للعرض فقط)'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='pipeline',
            field=models.CharField(choices=[('M', 'سوق المواشي'), ('S', 'الأضاحي'), ('G', 'تشارك عام')], max_length=1, verbose_name='الماسورة'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر في هذا القسم'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='section',
            field=models.CharField(choices=[('full_sale', 'بيع كامل'), ('adahi_pool', 'مسبح أضاحي'), ('adahi_full', 'أضحية كاملة'), ('adahi_group', 'مجموعة خاصة'), ('shares', 'تشارك لحم')], max_length=20, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='animallisting',
            name='total_shares',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الأسهم الكلي'),
        ),
        migrations.AlterField(
            model_name='category',
            name='default_max_shares',
            field=models.PositiveIntegerField(default=5, verbose_name='عدد الأسهم الافتراضي للتشارك العام'),
        ),
        migrations.AddIndex(
            model_name='animallisting',
            index=models.Index(fields=['pipeline', 'section', 'is_active'], name='livestock_a_pipelin_7dad1f_idx'),
        ),
        migrations.AddIndex(
            model_name='animallisting',
            index=models.Index(fields=['animal', 'is_active'], name='livestock_a_animal__eb9bd9_idx'),
        ),
    ]

