# Generated by Django 5.2.4 on 2026-03-24 22:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0022_remove_adahigroup_animal_remove_animal_is_adahi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='internal_image',
            field=models.ImageField(blank=True, null=True, upload_to='livestock_internal/', verbose_name='صورة الإثبات للمورد (مخفية)'),
        ),
    ]

