# Generated by Django 5.2.4 on 2026-03-31 10:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0023_animal_internal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animallisting',
            name='paused_due_to_order',
            field=models.BooleanField(default=False, verbose_name='موقوف مؤقتاً بسبب طلب'),
        ),
    ]

