# Generated by Django 5.2.4 on 2026-04-01 16:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0024_animallisting_paused_due_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='daily_delivery_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='الحد الأقصى للتوصيل في اليوم (0 = غير محدود)'),
        ),
        migrations.AddField(
            model_name='category',
            name='extra_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم توصيل إضافية للرأس (جنيه)'),
        ),
    ]

