# Generated by Django 5.2.4 on 2026-04-04 10:14

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0025_category_daily_delivery_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysetting',
            name='slaughter_preparation_days',
            field=models.PositiveIntegerField(default=4, help_text='عدد أيام التحضير (مذبوح)'),
        ),
        migrations.AlterField(
            model_name='deliverysetting',
            name='preparation_days',
            field=models.PositiveIntegerField(default=3, help_text='عدد أيام التحضير (حي)'),
        ),
    ]

