# Generated by Django 5.2.4 on 2025-09-10 02:06

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='أقصى نسبة خصم مسموحة (%)')),
            ],
            options={
                'verbose_name': 'دور الموظف',
                'verbose_name_plural': 'أدوار الموظفين',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الصنف')),
                ('type', models.CharField(choices=[('feed', 'علف'), ('medicine', 'دواء'), ('consumable', 'مستهلكات'), ('equipment', 'معدات')], max_length=20, verbose_name='نوع الصنف')),
                ('unit_of_measure', models.CharField(help_text='مثال: كجم، طن، لتر، علبة', max_length=50, verbose_name='وحدة القياس')),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=100, max_digits=12, verbose_name='حد الطلب الأدنى')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الموظف')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('national_id', models.CharField(max_length=14, unique=True, verbose_name='الرقم القومي')),
                ('birth_date', models.DateField(blank=True, editable=False, null=True, verbose_name='تاريخ الميلاد')),
                ('address', models.TextField(verbose_name='العنوان التفصيلي')),
                ('national_id_image', models.ImageField(blank=True, null=True, upload_to='national_ids/', verbose_name='صورة البطاقة')),
                ('is_phone_verified', models.BooleanField(default=True, verbose_name='Phone Verified')),
                ('is_email_verified', models.BooleanField(default=True, verbose_name='Email Verified')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ التعيين')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=True, verbose_name='عضو فريق عمل')),
                ('groups', models.ManyToManyField(blank=True, related_name='employee_groups', related_query_name='employee', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='employee_user_permissions', related_query_name='employee', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employeerole', verbose_name='الدور')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100, verbose_name='نوع الإجراء')),
                ('details', models.JSONField(default=dict, verbose_name='تفاصيل الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'تم الرفض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات القرار')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_approvals', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن الموافقة')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_approvals', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'طلب موافقة',
                'verbose_name_plural': 'طلبات الموافقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الغرفة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='المشاركون')),
            ],
            options={
                'verbose_name': 'غرفة محادثة',
                'verbose_name_plural': 'غرف المحادثات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='management.chatroom', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'رسالة محادثة',
                'verbose_name_plural': 'رسائل المحادثات',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hired', 'تم التعيين'), ('activated', 'تم التفعيل'), ('deactivated', 'تم إلغاء التفعيل')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل حالة الموظف',
                'verbose_name_plural': 'سجلات حالة الموظفين',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FarmDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, verbose_name='وصف القسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='صلاحيات القسم')),
            ],
            options={
                'verbose_name': 'Farm Department',
                'verbose_name_plural': 'Farm Departments',
                'permissions': [('view_dashboard', 'Can view management dashboard'), ('view_advanced_reports', 'Can view advanced KPI reports')],
            },
        ),
        migrations.AddField(
            model_name='employeerole',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='management.farmdepartment', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.farmdepartment', verbose_name='القسم'),
        ),
        migrations.CreateModel(
            name='FeedingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight_kg', models.PositiveIntegerField(verbose_name='أقل وزن (كجم)')),
                ('max_weight_kg', models.PositiveIntegerField(verbose_name='أقصى وزن (كجم)')),
                ('feed_percentage_of_body_weight', models.DecimalField(decimal_places=2, default=Decimal('2.5'), max_digits=5, verbose_name='نسبة العلف من وزن الجسم (%)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.category', verbose_name='فئة الحيوان')),
            ],
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(verbose_name='تاريخ السجل')),
                ('log_type', models.CharField(choices=[('vaccination', 'تطعيم'), ('treatment', 'علاج'), ('observation', 'ملاحظة')], max_length=100, verbose_name='نوع السجل')),
                ('description', models.TextField(verbose_name='الوصف/الدواء المستخدم')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة العلاج/الدواء')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='livestock.animal', verbose_name='الحيوان')),
                ('vet', models.ForeignKey(blank=True, limit_choices_to={'role__name__icontains': 'طبيب'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الكمية (كجم)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التغذية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='livestock.animal', verbose_name='الحيوان')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
                ('item', models.ForeignKey(limit_choices_to={'type': 'feed'}, on_delete=django.db.models.deletion.PROTECT, to='management.inventoryitem', verbose_name='نوع العلف')),
            ],
            options={
                'verbose_name': 'سجل تغذية',
                'verbose_name_plural': 'سجلات التغذية',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='الشهر')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='صافي الراتب')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مسير رواتب',
                'verbose_name_plural': 'مسيرات الرواتب',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('allowance', 'بدل'), ('deduction', 'خصم'), ('base_salary', 'راتب أساسي'), ('advance', 'سلفة')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='management.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_approval', 'بانتظار الموافقة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض'), ('received', 'تم الاستلام')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.approvalrequest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='management.inventoryitem')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ALLOW', 'ممنوح'), ('REQUIRE_APPROVAL', 'يتطلب موافقة')], default='ALLOW', max_length=20)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employeerole')),
            ],
            options={
                'verbose_name': 'صلاحية دور',
                'verbose_name_plural': 'صلاحيات الأدوار',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='employeerole',
            name='permissions',
            field=models.ManyToManyField(blank=True, through='management.RolePermission', to='auth.permission', verbose_name='الصلاحيات'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='الكمية')),
                ('movement_type', models.CharField(choices=[('purchase', 'استلام مشتريات'), ('feeding', 'صرف تغذية'), ('treatment', 'صرف علاج'), ('adjustment_in', 'تسوية إضافة'), ('adjustment_out', 'تسوية خصم/تالف')], max_length=20, verbose_name='نوع الحركة')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحركة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='management.inventoryitem', verbose_name='الصنف')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.inventorylot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المورد')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('item_supplied_description', models.TextField(blank=True, verbose_name='ماذا يورد (وصف)')),
                ('items_supplied', models.ManyToManyField(blank=True, related_name='suppliers', to='management.inventoryitem', verbose_name='الأصناف التي يوردها')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.supplier'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_inventory_items', to='management.supplier', verbose_name='المورد الأساسي'),
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الوزن')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='الوزن (كجم)')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='livestock.animal')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل وزن',
                'verbose_name_plural': 'سجلات الأوزان',
                'ordering': ['-date'],
            },
        ),
    ]

