# Generated by Django 5.2.4 on 2025-09-11 00:08

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmdepartment',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='صلاحيات القسم الافتراضية'),
        ),
    ]

