# Generated by Django 5.2.4 on 2025-09-11 00:10

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_farmdepartment_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='تمت القراءة'),
        ),
    ]

