# Generated by Django 5.2.4 on 2025-10-23 20:55

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_chatmessage_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'permissions': [('can_delete_any_message', 'Can delete any chat message')], 'verbose_name': 'رسالة محادثة', 'verbose_name_plural': 'رسائل المحادثات'},
        ),
    ]

