# Generated by Django 5.2.4 on 2025-10-23 21:11

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_persons',
            field=models.CharField(blank=True, help_text='خاص بمزارع المواشي', max_length=255, verbose_name='أسماء المسؤولين'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('LIVESTOCK_FARM', 'مزرعة مواشي'), ('GENERAL_SUPPLIER', 'مورد عام')], default='GENERAL_SUPPLIER', max_length=20, verbose_name='نوع المورد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='item_supplied_description',
            field=models.TextField(blank=True, help_text='خاص بالمورد العام (أعلاف، أدوية..)', verbose_name='ماذا يورد (وصف)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='items_supplied',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='management.inventoryitem', verbose_name='الأصناف التي يوردها (للمورد العام)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المورد / المزرعة'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف الأساسي'),
        ),
    ]

