# Generated by Django 5.2.4 on 2025-10-25 12:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_supplier_contact_persons_supplier_supplier_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='additional_contacts',
            field=models.TextField(blank=True, help_text='يمكنك إضافة أرقام هواتف متعددة هنا، كل رقم في سطر.', verbose_name='أرقام تواصل إضافية'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف الأساسي'),
        ),
    ]
