# Generated by Django 5.2.4 on 2025-12-05 13:52

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20251025_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowed_login_end',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت انتهاء السماح بالدخول'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allowed_login_start',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت بدء السماح بالدخول'),
        ),
        migrations.AddField(
            model_name='employee',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='مدة الجلسة (دقائق)'),
        ),
    ]

