# Generated by Django 5.2.4 on 2025-12-05 14:07

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_employee_allowed_login_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='allowed_login_end',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='allowed_login_start',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='session_timeout_minutes',
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_end',
            field=models.TimeField(blank=True, null=True, verbose_name='نهاية الوردية (مخصص)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start',
            field=models.TimeField(blank=True, null=True, verbose_name='بداية الوردية (مخصص)'),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='shift_end',
            field=models.TimeField(blank=True, null=True, verbose_name='نهاية الوردية'),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='shift_start',
            field=models.TimeField(blank=True, null=True, verbose_name='بداية الوردية'),
        ),
        migrations.AddField(
            model_name='farmdepartment',
            name='shift_end',
            field=models.TimeField(blank=True, null=True, verbose_name='نهاية الوردية'),
        ),
        migrations.AddField(
            model_name='farmdepartment',
            name='shift_start',
            field=models.TimeField(blank=True, null=True, verbose_name='بداية الوردية'),
        ),
    ]

