# Generated by Django 5.2.4 on 2025-12-05 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_employee_allowed_login_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='session_duration',
            field=models.PositiveIntegerField(default=0, help_text='مدة الجلسة بالدقائق (0 تعني وراثة)', verbose_name='مدة الجلسة (مخصص)'),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='session_duration',
            field=models.PositiveIntegerField(default=0, help_text='مدة الجلسة بالدقائق (0 تعني وراثة من القسم)', verbose_name='مدة الجلسة'),
        ),
        migrations.AddField(
            model_name='farmdepartment',
            name='session_duration',
            field=models.PositiveIntegerField(default=0, help_text='مدة الجلسة بالدقائق (0 تعني الافتراضي)', verbose_name='مدة الجلسة'),
        ),
        migrations.CreateModel(
            name='PasswordChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التغيير')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_passwords', to=settings.AUTH_USER_MODEL, verbose_name='قام بالتغيير')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_changes', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل تغيير كلمة المرور',
                'verbose_name_plural': 'سجلات تغيير كلمات المرور',
                'ordering': ['-timestamp'],
            },
        ),
    ]

