# Generated by Django 5.2.4 on 2025-12-05 16:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_employee_session_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='session_duration',
            field=models.PositiveIntegerField(default=0, help_text='مدة الجلسة بالساعات (0 تعني وراثة)', verbose_name='مدة الجلسة (ساعة)'),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='session_duration',
            field=models.PositiveIntegerField(default=0, help_text='مدة الجلسة بالساعات (0 تعني وراثة من القسم)', verbose_name='مدة الجلسة (ساعة)'),
        ),
        migrations.AlterField(
            model_name='farmdepartment',
            name='session_duration',
            field=models.PositiveIntegerField(default=0, help_text='مدة الجلسة بالساعات (0 تعني الافتراضي)', verbose_name='مدة الجلسة (ساعة)'),
        ),
        migrations.AlterField(
            model_name='passwordchangelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
    ]

