# Generated by Django 5.2.4 on 2025-12-06 05:40

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_employee_session_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تغيير لكلمة المرور'),
        ),
        migrations.AddField(
            model_name='employee',
            name='password_expiry_days',
            field=models.PositiveIntegerField(default=90, verbose_name='مدة صلاحية كلمة المرور (أيام)'),
        ),
    ]

