# Generated by Django 5.2.4 on 2025-12-06 05:53

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_employee_last_password_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordchangelog',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ملاحظات'),
        ),
    ]

