# Generated by Django 5.2.4 on 2025-12-06 06:06

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_passwordchangelog_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchangelog',
            name='notes',
            field=models.CharField(blank=True, default='No notes', max_length=255, verbose_name='ملاحظات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'استلام مشتويات'), ('feeding', 'صرف تغذية'), ('treatment', 'صرف علاج'), ('adjustment_in', 'تسوية إضافة'), ('adjustment_out', 'تسوية خصم/تالف')], max_length=20, verbose_name='نوع الحركة'),
        ),
    ]

