# Generated by Django 5.2.4 on 2025-12-06 10:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_passwordchangelog_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordchangelog',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC Address'),
        ),
    ]
