# Generated by Django 5.2.4 on 2025-12-06 10:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_passwordchangelog_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deactivation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب إلغاء التفعيل'),
        ),
    ]
