# Generated by Django 5.2.4 on 2025-12-06 12:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_employee_deactivation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatuslog',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='السبب'),
        ),
    ]
