# Generated by Django 5.2.4 on 2025-12-06 14:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_employeestatuslog_reason'),
    ]

    operations = [
        # This migration is empty but ensures Django's migration system
        # is aware of the previous changes if you already ran it.
        # If you did not run the previous migration, you can delete this file.
    ]
