# Generated by Django 5.2.4 on 2025-12-06 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_employeestatuslog_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التغيير')),
                ('old_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب القديم')),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الجديد')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='قام بالتغيير')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_changes', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل تغيير الراتب',
                'verbose_name_plural': 'سجلات تغيير الرواتب',
                'ordering': ['-timestamp'],
            },
        ),
    ]
