# Generated by Django 5.2.4 on 2025-12-11 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_discount_end_date_user_discount_start_date_and_more'),
        ('management', '0017_salarychangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'عميل محدد'), ('global', 'خصم عام')], max_length=10)),
                ('department_snapshot', models.CharField(blank=True, max_length=100, verbose_name='القسم وقت التغيير')),
                ('old_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='قام بالتغيير')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_logs', to='accounts.user')),
            ],
            options={
                'verbose_name': 'سجل الخصومات',
                'verbose_name_plural': 'سجلات الخصومات',
                'ordering': ['-timestamp'],
            },
        ),
    ]

