# Generated by Django 5.2.4 on 2025-12-12 07:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_discountlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'استلام مشتريات'), ('feeding', 'صرف تغذية'), ('treatment', 'صرف علاج'), ('adjustment_in', 'تسوية إضافة'), ('adjustment_out', 'تسوية خصم/تالف')], max_length=20, verbose_name='نوع الحركة'),
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حضور'), ('absent', 'غياب'), ('late', 'تأخير'), ('leave', 'أجازة')], default='present', max_length=20, verbose_name='الحالة')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='قام بالتسجيل')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]

