# Generated by Django 5.2.4 on 2025-12-16 15:13

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_stockmovement_movement_type_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
    ]

