# Generated by Django 5.2.4 on 2026-01-03 01:36

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_employeerole_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='المسمى الوظيفي')),
                ('job_type', models.CharField(choices=[('Full-time', 'دوام كامل'), ('Part-time', 'دوام جزئي'), ('Contract', 'عقد مؤقت'), ('Remote', 'عن بعد'), ('Shift-based', 'ورديات')], default='Full-time', max_length=50, verbose_name='نوع الوظيفة')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
                ('description', models.TextField(verbose_name='وصف الوظيفة')),
                ('requirements', models.TextField(help_text='كل نقطة في سطر جديد', verbose_name='المتطلبات')),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='نطاق الراتب')),
                ('vacancy_count', models.PositiveIntegerField(default=1, verbose_name='العدد المطلوب')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='آخر موعد للتقديم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط (مفتوح للتقديم)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المتقدم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('cv_link', models.URLField(verbose_name='رابط السيرة الذاتية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='management.jobopening', verbose_name='الوظيفة')),
            ],
            options={
                'verbose_name': 'طلب توظيف',
                'verbose_name_plural': 'طلبات التوظيف',
                'ordering': ['-created_at'],
            },
        ),
    ]

