# Generated by Django 5.2.4 on 2026-03-10 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_discount_max_animals_user_discount_used_animals_and_more'),
        ('management', '0021_jobopening_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة/الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user', verbose_name='العميل المسجل')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم العميل')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم العميل')),
                ('reason', models.CharField(choices=[('inquiry', 'استفسار عام'), ('order', 'بخصوص طلب/حجز'), ('complaint', 'شكوى/مشكلة'), ('partnership', 'طلب شراكة'), ('other', 'أخرى')], default='inquiry', max_length=20, verbose_name='سبب الاتصال')),
                ('status', models.CharField(choices=[('resolved', 'تم الحل/الانتهاء'), ('pending', 'قيد المتابعة')], default='resolved', max_length=20, verbose_name='حالة المكالمة')),
                ('notes', models.TextField(verbose_name='تفاصيل المكالمة وما تم فيها')),
                ('start_time', models.DateTimeField(verbose_name='بداية المكالمة')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='نهاية المكالمة')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='مدة المكالمة بالثواني')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
            ],
            options={
                'verbose_name': 'سجل مكالمة',
                'verbose_name_plural': 'سجلات المكالمات',
                'ordering': ['-start_time'],
            },
        ),
    ]

