# Generated by Django 5.2.4 on 2026-03-11 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_contactmessage_customercalllog'),
        ('orders', '0017_order_delivery_photo_order_is_paperwork_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المستند')),
                ('document_type', models.CharField(choices=[('supplier_contract', 'عقد مورد / مزرعة'), ('b2b_contract', 'عقد شركة / مطعم'), ('other', 'مستندات أخرى')], max_length=50, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='document_archive/', verbose_name='الملف/الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='orders.businessrequest')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='management.supplier')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة')),
            ],
            options={
                'verbose_name': 'أرشيف وثيقة',
                'verbose_name_plural': 'أرشيف الوثائق',
                'ordering': ['-created_at'],
            },
        ),
    ]

