# Generated by Django 5.2.4 on 2026-03-21 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_documentarchive'),
        ('orders', '0022_shipment_butcher_names_shipment_shipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentarchive',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='documentarchive',
            name='document_type',
            field=models.CharField(choices=[('supplier_contract', 'عقد مورد / مزرعة'), ('b2b_contract', 'عقد شركة / مطعم'), ('order_doc', 'مستند لطلب عميل (إيصال/تسليم)'), ('other', 'مستندات أخرى')], max_length=50, verbose_name='نوع المستند'),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المدفوع')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='management.supplier', verbose_name='المورد')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]

