# Generated by Django 5.2.4 on 2026-03-21 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_documentarchive_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentarchive',
            name='employee_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='documentarchive',
            name='external_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم جهة/شخص خارجي'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_contract_signed',
            field=models.BooleanField(default=False, verbose_name='تم توقيع العقد ورفعه'),
        ),
        migrations.AlterField(
            model_name='documentarchive',
            name='document_type',
            field=models.CharField(choices=[('supplier_contract', 'عقد مورد / مزرعة'), ('b2b_contract', 'عقد شركة / مطعم'), ('order_doc', 'مستند لطلب عميل (إيصال/تسليم)'), ('employee_doc', 'مستندات موظف (عقد/فيش/هوية)'), ('other', 'مستندات أخرى')], max_length=50, verbose_name='نوع المستند'),
        ),
        migrations.AlterField(
            model_name='documentarchive',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='تم الرفع بواسطة'),
        ),
    ]

