# Generated by Django 5.2.4 on 2026-03-21 05:48

import management.models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_documentarchive_employee_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentarchive',
            name='file',
            field=models.FileField(upload_to=management.models.document_archive_upload, verbose_name='الملف/الصورة'),
        ),
    ]

