# Generated by Django 5.2.4 on 2026-03-21 06:04

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_discount_max_animals_user_discount_used_animals_and_more'),
        ('management', '0026_alter_documentarchive_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentarchive',
            name='b2b_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_contracts', to='accounts.user', verbose_name='العميل التجاري'),
        ),
    ]

