# Generated by Django 5.2.4 on 2026-03-23 05:04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_documentarchive_b2b_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_receipts/', verbose_name='صورة الإيصال/التحويل'),
        ),
    ]

