# Generated by Django 5.2.4 on 2026-03-26 09:04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_supplierpayment_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentarchive',
            name='document_type',
            field=models.CharField(choices=[('supplier_contract', 'عقد مورد / مزرعة'), ('b2b_contract', 'عقد تعاقد شركة / مطعم'), ('b2b_order_doc', 'إذن استلام طلب شركات (B2B)'), ('order_doc', 'إيصال استلام طلب أفراد عادي'), ('employee_doc', 'مستندات موظف (عقد/فيش/هوية)'), ('other', 'مستندات أخرى')], max_length=50, verbose_name='نوع المستند'),
        ),
    ]

