# Generated by Django 5.2.4 on 2026-04-07 18:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_alter_documentarchive_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/', verbose_name='المرفق'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوفة'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('DIRECT', 'محادثة فردية'), ('GROUP', 'مجموعة'), ('DEPARTMENT', 'غرفة قسم')], default='DIRECT', max_length=20, verbose_name='نوع الغرفة'),
        ),
        migrations.AddField(
            model_name='farmdepartment',
            name='can_communicate_with',
            field=models.ManyToManyField(blank=True, to='management.farmdepartment', verbose_name='الأقسام المسموح بالتواصل معها'),
        ),
    ]

