# Generated by Django 5.2.4 on 2026-04-07 19:58

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_chatmessage_attachment_chatmessage_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'permissions': [('can_delete_any_message', 'Can delete any chat message'), ('can_view_all_chats', 'Can view all chats')], 'verbose_name': 'رسالة محادثة', 'verbose_name_plural': 'رسائل المحادثات'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reactions',
            field=models.JSONField(blank=True, default=dict, verbose_name='التفاعلات'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allowed_chat_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='موظفين مسموح بالتواصل معهم استثنائياً'),
        ),
    ]

