# Generated by Django 5.2.4 on 2026-04-08 07:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_alter_chatmessage_options_chatmessage_reactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='المحتوى'),
        ),
    ]

