# Generated by Django 5.2.4 on 2026-04-08 09:48

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='allowed_writers',
            field=models.ManyToManyField(blank=True, related_name='writable_rooms', to=settings.AUTH_USER_MODEL, verbose_name='المسموح لهم بالكتابة'),
        ),
    ]

