# Generated by Django 5.2.4 on 2026-04-08 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_chatroom_allowed_writers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_for_everyone_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_everyone_msgs', to=settings.AUTH_USER_MODEL, verbose_name='من قام بالحذف للجميع'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_for_users',
            field=models.ManyToManyField(blank=True, related_name='hidden_messages', to=settings.AUTH_USER_MODEL, verbose_name='حذفت لدى (فقط)'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف للجميع'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوفة للجميع'),
        ),
    ]

