# Generated by Django 5.2.4 on 2026-04-08 11:56

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_chatmessage_deleted_for_everyone_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_chat_blocked',
            field=models.BooleanField(default=False, verbose_name='موقوف من الشات'),
        ),
    ]

