# Generated by Django 5.2.4 on 2026-04-11 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_employee_is_chat_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='pending_data',
            field=models.JSONField(blank=True, help_text='البيانات الجديدة بانتظار الموافقة', null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='target_module',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ApprovalRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('livestock', 'إدارة المواشي'), ('orders', 'المبيعات والطلبات'), ('inventory', 'المخزون والموردين'), ('hr', 'الموارد البشرية والرواتب'), ('accounting', 'المالية والمحاسبة'), ('settings', 'الإعدادات العامة')], max_length=50, unique=True, verbose_name='وحدة النظام')),
                ('designated_approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن الموافقة')),
            ],
            options={
                'verbose_name': 'توجيه الموافقة',
                'verbose_name_plural': 'توجيهات الموافقات',
            },
        ),
        migrations.CreateModel(
            name='ModuleAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('livestock', 'إدارة المواشي'), ('orders', 'المبيعات والطلبات'), ('inventory', 'المخزون والموردين'), ('hr', 'الموارد البشرية والرواتب'), ('accounting', 'المالية والمحاسبة'), ('settings', 'الإعدادات العامة')], max_length=50, verbose_name='وحدة النظام')),
                ('access_level', models.CharField(choices=[('NO_ACCESS', 'لا يوجد وصول (مخفي)'), ('VIEW_ONLY', 'رؤية فقط'), ('FULL_ACCESS', 'تحكم كامل (إضافة/تعديل/حذف)'), ('REQUIRE_APPROVAL', 'تعديل وحذف بموافقة')], default='NO_ACCESS', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='management.farmdepartment')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='management.employeerole')),
            ],
            options={
                'verbose_name': 'قاعدة صلاحية',
                'verbose_name_plural': 'قواعد الصلاحيات',
            },
        ),
    ]

