# Generated by Django 5.2.4 on 2026-04-11 11:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_approvalrequest_pending_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleaccessrule',
            name='excluded_pages',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='الصفحات المحجوبة'),
        ),
    ]

