# Generated by Django 5.2.4 on 2026-04-11 13:12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_moduleaccessrule_excluded_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleaccessrule',
            name='access_level',
        ),
        migrations.AddField(
            model_name='moduleaccessrule',
            name='actions',
            field=models.JSONField(default=dict, verbose_name='تفاصيل الصلاحيات'),
        ),
    ]

