# Generated by Django 5.2.4 on 2026-04-17 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_discount_max_animals_user_discount_used_animals_and_more'),
        ('management', '0038_remove_moduleaccessrule_access_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNoteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='الملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_logs', to='accounts.user', verbose_name='العميل')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSuspensionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('suspended', 'إيقاف'), ('activated', 'تفعيل')], max_length=20, verbose_name='الإجراء')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspension_logs', to='accounts.user', verbose_name='العميل')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

