# Generated by Django 5.2.4 on 2026-04-20 21:58

import django.core.validators
import management.models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_customernotelog_customersuspensionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentarchive',
            name='file',
            field=models.FileField(upload_to=management.models.document_archive_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='الملف/الصورة'),
        ),
    ]

