# Generated by Django 5.2.4 on 2025-09-10 02:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'في انتظار الدفع'), ('confirmed', 'تم تأكيد الحجز'), ('cancelled', 'تم الإلغاء'), ('completed', 'تم التسليم والانتهاء')], default='pending', max_length=10)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية العربون أو الحجز إذا لم يتم الدفع الكامل', null=True)),
                ('paid_amount_on_booking', models.DecimalField(decimal_places=2, default=0, help_text='المبلغ المدفوع عند الحجز (عربون أو كامل)', max_digits=10)),
                ('total_calculated_price', models.DecimalField(decimal_places=2, default=0, help_text='السعر الإجمالي المحسوب للحجز بكل الخدمات والرسوم', max_digits=10)),
                ('remaining_amount_due', models.DecimalField(decimal_places=2, default=0, help_text='المبلغ المتبقي المطلوب دفعه', max_digits=10)),
                ('booking_type', models.CharField(choices=[('deposit', 'دفع عربون'), ('full', 'دفع كامل')], default='deposit', max_length=10)),
                ('delivery_option_type', models.CharField(blank=True, help_text='to_home, pickup', max_length=20, null=True)),
                ('slaughter_option_type', models.CharField(blank=True, help_text='live, slaughtered', max_length=20, null=True)),
                ('cutting_option', models.CharField(blank=True, help_text='yes, no', max_length=10, null=True)),
                ('packaging_option', models.CharField(blank=True, help_text='yes, no', max_length=10, null=True)),
                ('butcher_notes', models.TextField(blank=True, null=True)),
                ('client_services_options_ids', models.JSONField(blank=True, default=list, help_text='قائمة بـ IDs الخدمات الإضافية التي تم اختيارها', null=True)),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('booking_start_date', models.DateField(blank=True, null=True)),
                ('extended_duration_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='livestock.animal')),
                ('delivery_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_for_area', to='livestock.deliveryarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.user')),
            ],
            options={
                'ordering': ['-reserved_at'],
            },
        ),
    ]

