# Generated by Django 5.2.4 on 2025-12-10 18:03

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='share_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الأسهم'),
        ),
    ]

================================================================================
================================================================================

