# Generated by Django 5.2.4 on 2025-12-11 07:32

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('farm', 'مزرعة (مورد)'), ('business', 'نشاط تجاري (مطعم/فندق/جزارة)')], max_length=20, verbose_name='نوع الطلب')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الجهة/الشخص')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان/المنطقة')),
                ('details', models.TextField(help_text='للمزارع: عدد ونوع المواشي. للمطاعم: الكميات المتوقعة.', verbose_name='تفاصيل العرض/الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('contacted', 'تم التواصل'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طلب شراكة',
                'verbose_name_plural': 'طلبات الشراكة',
                'ordering': ['-created_at'],
            },
        ),
    ]

