version: '3'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  django:
    container_name: lahm_backend
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 life.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis


