# Generated by Django 5.2.4 on 2026-02-26 19:31

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_business_name_user_is_corporate'),
        ('orders', '0015_alter_orderitem_listing_section'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('initial', 'دفعة أولى/عربون'), ('remainder', 'باقي المبلغ')], default='initial', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'created_at'], name='payments_pa_user_id_5bbfc5_idx'),
        ),
    ]

