# Generated by Django 5.2.4 on 2026-03-31 10:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_recorded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
    ]

