# Generated by Django 5.2.4 on 2025-12-17 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('OTP', 'رمز التحقق (OTP)'), ('ORDER_CONFIRMED', 'تأكيد الطلب'), ('ORDER_SHIPPED', 'الطلب خرج للتوصيل'), ('ORDER_DELIVERED', 'تم تسليم الطلب'), ('DRIVER_NEAR', 'السائق بالقرب منك')], max_length=50, unique=True, verbose_name='نوع الرسالة')),
                ('content', models.TextField(help_text='استخدم الأقواس {} للمتغيرات. مثال: {name}', verbose_name='نص الرسالة')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20, verbose_name='المستلم')),
                ('content', models.TextField(verbose_name='نص الرسالة')),
                ('message_type', models.CharField(choices=[('OTP', 'OTP'), ('AUTOMATED', 'تلقائي (نظام)'), ('MANUAL', 'يدوي (أدمن)')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'تم الإرسال'), ('failed', 'فشل')], max_length=20)),
                ('provider_response', models.TextField(blank=True, null=True, verbose_name='رد المزود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مرسلة بواسطة')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

