# Generated by Django 5.2.4 on 2026-04-09 18:07

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='message_type',
            field=models.CharField(choices=[('OTP', 'OTP'), ('AUTOMATED', 'تلقائي (نظام)'), ('MANUAL', 'يدوي (أدمن)'), ('EMAIL', 'بريد إلكتروني')], max_length=20),
        ),
    ]

