# Generated by Django 5.2.4 on 2025-12-11 09:46

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDiscountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='تفعيل الخصم العام')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم العام (%)')),
                ('applies_to_services', models.BooleanField(default=False, verbose_name='يشمل الخدمات')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('ticker_message', models.CharField(default='عرض خاص لفترة محدودة!', max_length=255, verbose_name='نص الشريط المتحرك')),
            ],
            options={
                'verbose_name': 'إعدادات الخصم العام',
                'verbose_name_plural': 'إعدادات الخصم العام',
            },
        ),
    ]

