# Generated by Django 5.2.4 on 2025-12-11 12:50

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_globaldiscountsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldiscountsettings',
            name='ticker_message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نص الشريط المتحرك'),
        ),
    ]

