# Generated by Django 5.2.4 on 2025-12-16 18:40

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_globaldiscountsettings_ticker_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_internal_slaughter', models.BooleanField(default=True, verbose_name='تفعيل الذبح الداخلي بالمزرعة')),
                ('enable_cutting_service', models.BooleanField(default=True, verbose_name='تفعيل خدمة التقطيع')),
                ('enable_packaging_service', models.BooleanField(default=True, verbose_name='تفعيل خدمة التغليف')),
                ('enable_delivery_service', models.BooleanField(default=True, verbose_name='تفعيل خدمة التوصيل')),
                ('contract_template', models.TextField(blank=True, default='بموجب هذا العقد تم الاتفاق بين شركة لحم وبين العميل {customer_name}...', help_text='استخدم {customer_name}, {order_id}, {date} كمتغيرات', verbose_name='نص عقد التوريد')),
                ('delivery_note_template', models.TextField(blank=True, default='أقر أنا الموقع أدناه باستلام الطلب بحالة جيدة ومطابقة للمواصفات.', help_text='النص الذي يظهر في إذن الاستلام للتوقيع عليه', verbose_name='نص إذن الاستلام')),
                ('invoice_footer_text', models.TextField(blank=True, default='تطبق الشروط والأحكام. البضاعة المباعة لا ترد ولا تستبدل إلا في حالة عيوب الصناعة.', help_text='الشروط والأحكام المختصرة أسفل الفاتورة', verbose_name='تذييل الفاتورة')),
            ],
            options={
                'verbose_name': 'إعدادات التشغيل',
                'verbose_name_plural': 'إعدادات التشغيل',
            },
        ),
    ]

