# Generated by Django 5.2.4 on 2025-12-16 20:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_operationsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationsettings',
            options={'verbose_name': 'إعدادات التشغيل والوثائق', 'verbose_name_plural': 'إعدادات التشغيل والوثائق'},
        ),
        migrations.RemoveField(
            model_name='operationsettings',
            name='invoice_footer_text',
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='invoice_footer',
            field=models.TextField(blank=True, default='تطبق الشروط والأحكام. البضاعة المباعة لا ترد ولا تستبدل.', verbose_name='تذييل الفاتورة'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='contract_template',
            field=models.TextField(blank=True, default='بموجب هذا العقد تم الاتفاق بين شركة لحم وبين العميل {customer_name}...', help_text='المتغيرات المتاحة: {customer_name}, {order_id}, {date}, {total_amount}, {items_list}', verbose_name='قالب عقد التوريد'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='delivery_note_template',
            field=models.TextField(blank=True, default='أقر أنا الموقع أدناه باستلام الطلب بحالة جيدة...', help_text='المتغيرات المتاحة: {customer_name}, {order_id}, {date}', verbose_name='قالب إذن الاستلام'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='enable_cutting_service',
            field=models.BooleanField(default=True, verbose_name='تفعيل خدمة التقطيع (المتجر)'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='enable_delivery_service',
            field=models.BooleanField(default=True, verbose_name='تفعيل خدمة التوصيل (المتجر)'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='enable_internal_slaughter',
            field=models.BooleanField(default=True, verbose_name='تفعيل الذبح الداخلي (المجزر الخاص)'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='enable_packaging_service',
            field=models.BooleanField(default=True, verbose_name='تفعيل خدمة التغليف (المتجر)'),
        ),
    ]

