# Generated by Django 5.2.4 on 2025-12-19 20:12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_operationsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='eid_adha_date',
            field=models.DateTimeField(blank=True, help_text='يستخدم لحساب صلاحية الأضحية وتوقع الأوزان', null=True, verbose_name='تاريخ عيد الأضحى القادم'),
        ),
    ]

