# Generated by Django 5.2.4 on 2025-12-20 12:48

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_operationsettings_eid_adha_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='enable_eid_celebration',
            field=models.BooleanField(default=False, help_text='تفعيل تأثيرات الزينة والقصاصات في الصفحة الرئيسية', verbose_name='تفعيل وضع احتفال العيد (زينة)'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='show_eid_timer',
            field=models.BooleanField(default=False, help_text='إظهار عداد الوقت المتبقي على العيد في الصفحة الرئيسية', verbose_name='إظهار عداد العيد التنازلي'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='contract_template',
            field=models.TextField(blank=True, default='بموجب هذا العقد تم الاتفاق بين شركة لحم وبين العميل {customer_name}...', verbose_name='قالب عقد التوريد'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='delivery_note_template',
            field=models.TextField(blank=True, default='أقر أنا الموقع أدناه باستلام الطلب بحالة جيدة...', verbose_name='قالب إذن الاستلام'),
        ),
    ]

