# Generated by Django 5.2.4 on 2025-12-21 20:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_operationsettings_enable_eid_celebration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='eid_fitr_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ عيد الفطر'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='enable_eid_fitr_celebration',
            field=models.BooleanField(default=False, verbose_name='تفعيل احتفال عيد الفطر'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='enable_ramadan_celebration',
            field=models.BooleanField(default=False, verbose_name='تفعيل احتفال رمضان (زينة وفوانيس)'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='ramadan_start_date',
            field=models.DateTimeField(blank=True, help_text='يستخدم لتحديد مدة الشهر الكريم', null=True, verbose_name='تاريخ بداية رمضان'),
        ),
    ]

