# Generated by Django 5.2.4 on 2025-12-29 20:22

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_operationsettings_eid_fitr_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='is_adahi_season_active',
            field=models.BooleanField(default=False, help_text='عند التفعيل، ستظهر صفحة الأضاحي في الموقع. عند الإلغاء، ستظهر رسالة أنها مغلقة.', verbose_name='تفعيل موسم الأضاحي (فتح الصفحة)'),
        ),
    ]

