# Generated by Django 5.2.4 on 2026-01-01 14:24

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_operationsettings_is_adahi_season_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='business_weight_margin',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='الزيادة أو النقصان المسموح به في الوزن لأوامر الشركات (± كجم)', max_digits=5, verbose_name='هامش الوزن المقبول (كجم)'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='min_business_order_quantity',
            field=models.PositiveIntegerField(default=5, help_text='الحد الأدنى لعدد الرؤوس المطلوبة عند حجز الأضاحي لقطاع الأعمال', verbose_name='أقل عدد رؤوس لطلب الشركات'),
        ),
    ]

