# Generated by Django 5.2.4 on 2026-03-03 04:12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_operationsettings_business_weight_margin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='enable_farm_pickup',
            field=models.BooleanField(default=True, verbose_name='تفعيل الاستلام من المزرعة (المتجر)'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='enable_slaughter_service',
            field=models.BooleanField(default=True, verbose_name='تفعيل خدمة الذبح للعملاء (المتجر)'),
        ),
    ]

