# Generated by Django 5.2.4 on 2026-03-03 05:13

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_operationsettings_enable_farm_pickup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='enable_adahi_full',
            field=models.BooleanField(default=True, verbose_name='تفعيل تبويب أضحية كاملة'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='enable_adahi_group',
            field=models.BooleanField(default=True, verbose_name='تفعيل تبويب المجموعات الخاصة'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='enable_adahi_pool',
            field=models.BooleanField(default=True, verbose_name='تفعيل تبويب مسبح الأضاحي'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='enable_general_shares',
            field=models.BooleanField(default=True, verbose_name='تفعيل صفحة التشارك العام'),
        ),
    ]

