# Generated by Django 5.2.4 on 2026-03-09 23:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_operationsettings_enable_adahi_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaldiscountsettings',
            name='max_animals_per_user',
            field=models.PositiveIntegerField(default=0, verbose_name='الحد الأقصى للمواشي لكل عميل (0=مفتوح)'),
        ),
    ]

