# Generated by Django 5.2.4 on 2026-03-14 21:59

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_globaldiscountsettings_max_animals_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='enable_fridge_manager',
            field=models.BooleanField(default=True, verbose_name='تفعيل شاشة الثلاجة والتغليف'),
        ),
    ]

