# Generated by Django 5.2.4 on 2026-03-21 04:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_operationsettings_enable_fridge_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationsettings',
            options={'verbose_name': 'إعدادات التشغيل', 'verbose_name_plural': 'إعدادات التشغيل'},
        ),
        migrations.RemoveField(
            model_name='operationsettings',
            name='contract_template',
        ),
        migrations.RemoveField(
            model_name='operationsettings',
            name='delivery_note_template',
        ),
        migrations.RemoveField(
            model_name='operationsettings',
            name='invoice_footer',
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='business_weight_margin',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='هامش الوزن المقبول (كجم)'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='eid_adha_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ عيد الأضحى القادم'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='enable_eid_celebration',
            field=models.BooleanField(default=False, verbose_name='تفعيل وضع احتفال العيد (زينة)'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='is_adahi_season_active',
            field=models.BooleanField(default=False, verbose_name='تفعيل موسم الأضاحي (فتح الصفحة)'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='min_business_order_quantity',
            field=models.PositiveIntegerField(default=5, verbose_name='أقل عدد رؤوس لطلب الشركات'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='ramadan_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بداية رمضان'),
        ),
        migrations.AlterField(
            model_name='operationsettings',
            name='show_eid_timer',
            field=models.BooleanField(default=False, verbose_name='إظهار عداد العيد التنازلي'),
        ),
    ]

