# Generated by Django 5.2.4 on 2026-03-23 05:42

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_operationsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='allow_deposit_payment',
            field=models.BooleanField(default=True, verbose_name='السماح بدفع العربون (الدفع الجزئي)'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='enable_eid_receive_button',
            field=models.BooleanField(default=False, verbose_name='إظهار زر الاستلام أيام العيد'),
        ),
    ]

