# Generated by Django 5.2.4 on 2026-03-25 02:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_operationsettings_allow_deposit_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='enable_slaughter_video_request',
            field=models.BooleanField(default=True, verbose_name='تفعيل طلب فيديو الذبح للعملاء'),
        ),
    ]

