# Generated by Django 5.2.4 on 2026-03-31 16:17

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_operationsettings_enable_slaughter_video_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='pricing_model',
            field=models.CharField(choices=[('care_fee', 'نظام الرعاية اليومية (سعر ثابت)'), ('live_weight', 'نظام الميزان الفعلي (القايم)')], default='care_fee', max_length=20, verbose_name='نظام تسعير وتسليم المواشي'),
        ),
    ]

