# Generated by Django 5.2.4 on 2026-04-01 16:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_operationsettings_pricing_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='delivery_limit_tolerance',
            field=models.PositiveIntegerField(default=2, verbose_name='نسبة التجاوز المسموحة للحد اليومي (رؤوس)'),
        ),
    ]

