# Generated by Django 5.2.4 on 2026-04-21 18:36

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_operationsettings_delivery_limit_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsettings',
            name='general_sms_provider',
            field=models.CharField(choices=[('whysms', 'WhySMS'), ('wesms', 'WeSMS'), ('mock', 'وهمي (Mock - للطباعة في الكونسول فقط)')], default='whysms', max_length=20, verbose_name='مزود خدمة الرسائل العامة (SMS)'),
        ),
        migrations.AddField(
            model_name='operationsettings',
            name='otp_provider',
            field=models.CharField(choices=[('whysms', 'WhySMS'), ('wesms', 'WeSMS'), ('mock', 'وهمي (Mock - للطباعة في الكونسول فقط)')], default='whysms', max_length=20, verbose_name='مزود خدمة رسائل الـ OTP'),
        ),
    ]

